name: Build CradleAI Android App

on:
  # 当有代码推送到 main 分支时触发
  push:
    branches: [ "main" ]
  # 允许你在 GitHub Actions 页面手动触发
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出你的代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # 使用 Node.js 18 版本
          cache: 'npm'

      # 3. 设置 Java (JDK) 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4. 安装项目依赖
      - name: Install dependencies
        run: npm install

      # 5. 解码并配置签名密钥
      - name: Decode Keystore
        run: |
          echo ${{ secrets.ANDROID_KEYSTORE }} | base64 --decode > ./android/app/cradleai-release-key.jks

      # 6. 使用 Gradle 构建 Release APK
      # 注意：我们在 gradle.properties 中引用了 GitHub Secrets
      - name: Build Release APK
        run: |
          cd android
          ./gradlew assembleRelease \
            -PkeystoreFile=cradleai-release-key.jks \
            -PkeystorePassword=${{ secrets.KEYSTORE_PASSWORD }} \
            -PkeyAlias=${{ secrets.KEY_ALIAS }} \
            -PkeyPassword=${{ secrets.KEY_PASSWORD }}
          cd ..

      # 7. 上传构建产物 (APK)
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CradleAI-release-unsigned # 我们需要重命名为 signed
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk # Gradle 默认生成未签名的，需要手动签名

      # 8. 签名 APK
      - name: Sign APK
        run: |
          jarsigner -verbose \
            -sigalg SHA1withRSA \
            -digestalg SHA1 \
            -keystore ./android/app/cradleai-release-key.jks \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            ./android/app/build/outputs/apk/release/app-release-unsigned.apk ${{ secrets.KEY_ALIAS }}

      # 9. 重命名已签名的 APK
      - name: Rename Signed APK
        run: |
          mv ./android/app/build/outputs/apk/release/app-release-unsigned.apk ./android/app/build/outputs/apk/release/CradleAI-v1.0.0-release-signed.apk

      # 10. 上传最终签名的 APK
      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: CradleAI-release-signed
          path: android/app/build/outputs/apk/release/CradleAI-v1.0.0-release-signed.apk
